sunbookpages = {
    {
        name = "cover",
        page = "mods/souls/files/sunbook/cover.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "intro",
        page = "mods/souls/files/sunbook/intro.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "sun",
        page = "mods/souls/files/sunbook/sun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "darksun",
        page = "mods/souls/files/sunbook/darksun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "greensun",
        page = "mods/souls/files/sunbook/greensun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "redsun",
        page = "mods/souls/files/sunbook/redsun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "redsun_revive",
        page = "mods/souls/files/sunbook/reviveboss.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "souldoor",
        page = "mods/souls/files/sunbook/souldoor.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "phylactery",
        page = "mods/souls/files/sunbook/phylactery.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    --[[{
        name = "bluesun",
        page = "mods/souls/files/sunbook/bluesun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },]]
}

rosettas = {
    {
        name = "rosetta1",
        page = "mods/souls/files/sunbook/rosettas/1.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta2",
        page = "mods/souls/files/sunbook/rosettas/2.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta3",
        page = "mods/souls/files/sunbook/rosettas/3.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta4",
        page = "mods/souls/files/sunbook/rosettas/4.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta5",
        page = "mods/souls/files/sunbook/rosettas/5.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta6",
        page = "mods/souls/files/sunbook/throngler.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta7",
        page = "mods/souls/files/sunbook/rosettas/7.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta8",
        page = "mods/souls/files/sunbook/rosettas/8.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta9",
        page = "mods/souls/files/sunbook/rosettas/9.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta10",
        page = "mods/souls/files/sunbook/rosettas/10.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "rosetta11",
        page = "mods/souls/files/sunbook/rosettas/11.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
}

traces = {
    {
        name = "ikkuna_alchemist",
        page = "mods/souls/files/sunbook/traces/alchemist.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_dragon",
        page = "mods/souls/files/sunbook/traces/dragon.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_wizard",
        page = "mods/souls/files/sunbook/traces/grandmaster.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_robot",
        page = "mods/souls/files/sunbook/traces/robot.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_squid",
        page = "mods/souls/files/sunbook/traces/squid.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_kolmi",
        page = "mods/souls/files/sunbook/traces/kolmi.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_souldoor",
        page = "mods/souls/files/sunbook/traces/souldoor.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
    {
        name = "ikkuna_valkoinen",
        page = "mods/souls/files/sunbook/traces/valkoinen.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = false,
    },
}

unlocked_sbp = {
    {
        name = "cover",
        page = "mods/souls/files/sunbook/cover.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    --[[{
        name = "intro",
        page = "mods/souls/files/sunbook/intro.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "sun",
        page = "mods/souls/files/sunbook/sun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "darksun",
        page = "mods/souls/files/sunbook/darksun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "greensun",
        page = "mods/souls/files/sunbook/greensun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "redsun",
        page = "mods/souls/files/sunbook/redsun.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },
    {
        name = "redsun_revive",
        page = "mods/souls/files/sunbook/reviveboss.png",
        scaleX = 1,
        scaleY = 1,
        unlocked = true,
    },]]
}